// DO NOT EDIT - Code generated by firemodel (dev).
import { firestore } from 'firebase';

// tslint:disable-next-line:no-namespace
export namespace  {
  type URL = string;

  export interface IFile {
    url: URL;
    mimeType: string;
    name: string;
  }