version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/mickeyreiss/firemodel
    steps:
      - checkout
      - run: make setup
      - run: make check
