// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

type Attachment struct {
	Title   string            `firestore:"title,omitempty"`
	Content AttachmentContent `firestore:"content,omitempty"`
}
