// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// for enum values other than the active one are not written to firestore.
type AttachmentContent string

const (
	// e.g. for an Attachment, written as `content = "PLACEHOLDER"`
	AttachmentContent_PLACEHOLDER AttachmentContent = "PLACEHOLDER"
	// e.g. for an Attachment, written as `content = "IMOJI", content.imoji = #BYTES#`
	AttachmentContent_IMOJI AttachmentContent = "IMOJI"
	// e.g. for an Attachment, written as `content = "IMOJI", content.imoji = #BYTES#`
	AttachmentContent_GRAM AttachmentContent = "GRAM"
	// e.g. for an Attachment, written as `content = "UPLOAD", content.upload.token = "oijasdf", content.upload.etc = the_rest`
	AttachmentContent_UPLOAD AttachmentContent = "UPLOAD"
)

var AttachmentContent_Strings = map[AttachmentContent]string{AttachmentContent_PLACEHOLDER: "AttachmentContent_PLACEHOLDER", AttachmentContent_IMOJI: "AttachmentContent_IMOJI", AttachmentContent_GRAM: "AttachmentContent_GRAM", AttachmentContent_UPLOAD: "AttachmentContent_UPLOAD"}
var AttachmentContent_Values = map[string]AttachmentContent{"AttachmentContent_PLACEHOLDER": AttachmentContent_PLACEHOLDER, "AttachmentContent_IMOJI": AttachmentContent_IMOJI, "AttachmentContent_GRAM": AttachmentContent_GRAM, "AttachmentContent_UPLOAD": AttachmentContent_UPLOAD}

func (e AttachmentContent) String() string {
	return AttachmentContent_Strings[e]
}
