// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// [unchanged] Enums provide type safety around string enumerations. Enums are stored in firestore as capitalized strings.
type Audience string

const (
	//
	Audience_GLOBAL Audience = "GLOBAL"
	//
	Audience_FRIENDS Audience = "FRIENDS"
)

var Audience_Strings = map[Audience]string{Audience_GLOBAL: "Audience_GLOBAL", Audience_FRIENDS: "Audience_FRIENDS"}
var Audience_Values = map[string]Audience{"Audience_GLOBAL": Audience_GLOBAL, "Audience_FRIENDS": Audience_FRIENDS}

func (e Audience) String() string {
	return Audience_Strings[e]
}
