// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

import runtime "github.com/visor-tax/firemodel/runtime"

// firestore client libraries.
type Avatar struct {
	Url   runtime.URL `firestore:"url,omitempty"`
	Color string      `firestore:"color,omitempty"`
}
