// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

import runtime "github.com/visor-tax/firemodel/runtime"

type Gram struct {
	SharedWith  Audience    `firestore:"sharedWith,omitempty"`
	PhotoUrl    runtime.URL `firestore:"photoUrl,omitempty"`
	Description string      `firestore:"description,omitempty"`
}
