// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// Firestore document location: /localized_string/{localized_string}
type LocalizedString struct {
	Strings map[string]string `firestore:"strings,omitempty"`
}
