// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

type MessageContent string

const (
	MessageContent_TEXT  MessageContent = "TEXT"
	MessageContent_PHOTO MessageContent = "PHOTO"
)

var MessageContent_Strings = map[MessageContent]string{MessageContent_TEXT: "MessageContent_TEXT", MessageContent_PHOTO: "MessageContent_PHOTO"}
var MessageContent_Values = map[string]MessageContent{"MessageContent_TEXT": MessageContent_TEXT, "MessageContent_PHOTO": MessageContent_PHOTO}

func (e MessageContent) String() string {
	return MessageContent_Strings[e]
}
