// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

import firestore "cloud.google.com/go/firestore"

type Client struct {
	Client *firestore.Client
}

func NewClient(client *firestore.Client) *Client {
	temp := &Client{Client: client}
	return temp
}
