// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

import runtime "github.com/visor-tax/firemodel/runtime"

type PhotoMessageContent struct {
	Caption string      `firestore:"caption,omitempty"`
	Url     runtime.URL `firestore:"url,omitempty"`
}
