// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

import runtime "github.com/visor-tax/firemodel/runtime"

type UploadAttachment struct {
	Title string      `firestore:"title,omitempty"`
	Src   runtime.URL `firestore:"src,omitempty"`
}
