// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

import runtime "github.com/visor-tax/firemodel/runtime"

type Upload struct {
	Url      runtime.URL `firestore:"url,omitempty"`
	MimeType string      `firestore:"mimeType,omitempty"`
}
