// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// TODO: Add comment to Direction
type Direction string

const (
	Direction_LEFT  Direction = "LEFT"
	Direction_RIGHT Direction = "RIGHT"
	Direction_UP    Direction = "UP"
	Direction_DOWN  Direction = "DOWN"
)
