// DO NOT EDIT - Code generated by firemodel.

package firemodel

// TODO: Add comment to Direction
type Direction int

const (
	// NOTE: This will shortly change back to "Direction_LEFT"
	Direction_LEFT Direction = 0
	// NOTE: This will shortly change back to "Direction_RIGHT"
	Direction_RIGHT Direction = 1
	// NOTE: This will shortly change back to "Direction_UP"
	Direction_UP Direction = 2
	// NOTE: This will shortly change back to "Direction_DOWN"
	Direction_DOWN Direction = 3
)
