// DO NOT EDIT - Code generated by firemodel.

import firebase from 'firebase';

export namespace example {
  type URL = string;

  export interface IFile {
    url: URL;
    mimeType: string;
    name: string;
  }

  export interface DocumentReference<T> extends firebase.firestore.DocumentReference {
  }

  /** TODO: Add documentation to Direction. */
  export enum Direction {
    /** TODO: Add documentation to left. */
    left = "LEFT",
    /** TODO: Add documentation to right. */
    right = "RIGHT",
    /** TODO: Add documentation to up. */
    up = "UP",
    /** TODO: Add documentation to down. */
    down = "DOWN",
  }

  /** A Test is a test model. */
  export interface ITestModel {
    /** TODO: Add documentation to nested. */
    nested: firebase.firestore.CollectionReference<ITestModel>;
    /** The name. */
    name: string;
    /** The age. */
    age: number;
    /** The number pi. */
    pi: number;
    /** The birth date. */
    birthdate: firebase.firestore.Timestamp;
    /** True if it is good. */
    isGood: boolean;
    /** TODO: Add documentation to data. */
    data: firebase.firestore.Blob;
    /** TODO: Add documentation to friend. */
    friend: DocumentReference<ITestModel>;
    /** TODO: Add documentation to location. */
    location: firebase.firestore.GeoPoint;
    /** TODO: Add documentation to colors. */
    colors: string[];
    /** TODO: Add documentation to meta. */
    meta: { [key: string]: any; };
    /** TODO: Add documentation to direction. */
    direction: Direction;
    /** TODO: Add documentation to test_file. */
    testFile: IFile;
    /** TODO: Add documentation to url. */
    url: URL;
  }
}
