// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// TODO: Add comment to TestDirection
type TestDirection string

const (
	// TODO: Add comment to TestDirection_LEFT.
	TestDirection_LEFT TestDirection = "LEFT"
	// TODO: Add comment to TestDirection_RIGHT.
	TestDirection_RIGHT TestDirection = "RIGHT"
	// TODO: Add comment to TestDirection_UP.
	TestDirection_UP TestDirection = "UP"
	// TODO: Add comment to TestDirection_DOWN.
	TestDirection_DOWN TestDirection = "DOWN"
)
