// DO NOT EDIT - Code generated by firemodel.

package firemodel

// TODO: Add comment to TestDirection
type TestDirection string

const (
	TestDirection_LEFT  TestDirection = "LEFT"
	TestDirection_RIGHT TestDirection = "RIGHT"
	TestDirection_UP    TestDirection = "UP"
	TestDirection_DOWN  TestDirection = "DOWN"
)
