// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// TODO: Add comment to &{TestStruct  [%!s(*firemodel.SchemaField=&{where  0x1471180}) %!s(*firemodel.SchemaField=&{how_much  0x1471180})]}
type TestStruct struct {
	// TODO: Add comment to TestStruct.where.
	Where string `firestore:"where"`
	// TODO: Add comment to TestStruct.how_much.
	HowMuch int64 `firestore:"howMuch"`
}
