// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

type TestEnum string

const (
	TestEnum_LEFT  TestEnum = "LEFT"
	TestEnum_RIGHT TestEnum = "RIGHT"
	TestEnum_UP    TestEnum = "UP"
	TestEnum_DOWN  TestEnum = "DOWN"
	TestEnum_OTHER TestEnum = "OTHER"
)

var TestEnum_Strings = map[TestEnum]string{TestEnum_LEFT: "TestEnum_LEFT", TestEnum_RIGHT: "TestEnum_RIGHT", TestEnum_UP: "TestEnum_UP", TestEnum_DOWN: "TestEnum_DOWN", TestEnum_OTHER: "TestEnum_OTHER"}
var TestEnum_Values = map[string]TestEnum{"TestEnum_LEFT": TestEnum_LEFT, "TestEnum_RIGHT": TestEnum_RIGHT, "TestEnum_UP": TestEnum_UP, "TestEnum_DOWN": TestEnum_DOWN, "TestEnum_OTHER": TestEnum_OTHER}

func (e TestEnum) String() string {
	return TestEnum_Strings[e]
}
