// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

import (
	firestore "cloud.google.com/go/firestore"
	runtime "github.com/visor-tax/firemodel/runtime"
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	"time"
)

// A Test is a test model.
// Firestore document location: /test_models/{test_model_id}
type TestModel struct {
	// The name.
	Name string `firestore:"name,omitempty"`
	// The age.
	Age int64 `firestore:"age"`
	// The number pi.
	Pi float64 `firestore:"pi"`
	// The birth date.
	Birthdate time.Time `firestore:"birthdate,omitempty"`
	// True if it is good.
	IsGood     bool                     `firestore:"isGood"`
	Data       []byte                   `firestore:"data,omitempty"`
	Friend     *firestore.DocumentRef   `firestore:"friend,omitempty"`
	Location   *latlng.LatLng           `firestore:"location,omitempty"`
	Colors     []string                 `firestore:"colors,omitempty"`
	Numbers    []int64                  `firestore:"numbers,omitempty"`
	Bools      []bool                   `firestore:"bools,omitempty"`
	Doubles    []float64                `firestore:"doubles,omitempty"`
	Directions []TestEnum               `firestore:"directions,omitempty"`
	Models     []*TestStruct            `firestore:"models,omitempty"`
	Models2    []*TestStruct            `firestore:"models2,omitempty"`
	ModelRefs  []*firestore.DocumentRef `firestore:"modelRefs,omitempty"`
	Meta       map[string]string        `firestore:"meta,omitempty"`
	Direction  TestEnum                 `firestore:"direction,omitempty"`
	TestFile   *runtime.File            `firestore:"testFile,omitempty"`
	Url        runtime.URL              `firestore:"url,omitempty"`
	Nested     *TestStruct              `firestore:"nested,omitempty"`
}
