// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// TODO: Add comment to TestDirection in firemodel schema.
type TestDirection string

const (
	// TODO: Add comment to TestDirection_LEFT in firemodel schema.
	TestDirection_LEFT TestDirection = "LEFT"
	// TODO: Add comment to TestDirection_RIGHT in firemodel schema.
	TestDirection_RIGHT TestDirection = "RIGHT"
	// TODO: Add comment to TestDirection_UP in firemodel schema.
	TestDirection_UP TestDirection = "UP"
	// TODO: Add comment to TestDirection_DOWN in firemodel schema.
	TestDirection_DOWN TestDirection = "DOWN"
)
