// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// TODO: Add comment to TestEnum in firemodel schema.
type TestEnum string

const (
	// TODO: Add comment to TestEnum_LEFT in firemodel schema.
	TestEnum_LEFT TestEnum = "LEFT"
	// TODO: Add comment to TestEnum_RIGHT in firemodel schema.
	TestEnum_RIGHT TestEnum = "RIGHT"
	// TODO: Add comment to TestEnum_UP in firemodel schema.
	TestEnum_UP TestEnum = "UP"
	// TODO: Add comment to TestEnum_DOWN in firemodel schema.
	TestEnum_DOWN TestEnum = "DOWN"
)
