// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

type TestStruct struct {
	Where    string   `firestore:"where,omitempty"`
	HowMuch  int64    `firestore:"howMuch"`
	SomeEnum TestEnum `firestore:"someEnum,omitempty"`
}
