// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// TODO: Add comment to TestDirection
type TestDirection int

const (
	// NOTE: This will shortly change back to "TestDirection_LEFT"
	TestDirection_LEFT TestDirection = 0
	// NOTE: This will shortly change back to "TestDirection_RIGHT"
	TestDirection_RIGHT TestDirection = 1
	// NOTE: This will shortly change back to "TestDirection_UP"
	TestDirection_UP TestDirection = 2
	// NOTE: This will shortly change back to "TestDirection_DOWN"
	TestDirection_DOWN TestDirection = 3
)
