// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

// Firestore document location: /test_timestamps/{test_timestamp_id}
type Test struct {
	Direction TestEnum `firestore:"direction,omitempty"`
}
