// DO NOT EDIT - Code generated by firemodel (dev).

package firemodel

import "time"

// TODO: Add comment to TestTimestamps
type TestTimestamps struct {

	// Creation timestamp.
	CreatedAt time.Time `firestore:"createdAt,serverTimestamp"`
	// Update timestamp.
	UpdatedAt time.Time `firestore:"updatedAt,serverTimestamp"`
}
